typography_spectrum: 0.41560873304493723
color:
  brandColors:
    - '#8CC63E'
    - '#00BFF3'
    - '#F15927'
    - '#434343'
    - '#FEFFFF'
  brandStrength: 0.5212071022929827
  lightness: 0.03891840575253683
  saturation: 0.6427184913068604
  rhythmicContrast: 0.6041641040064284
github: true
layout_spectrum: 0.7624284483256316
author:
  name: eSecurity Consulting Servces
  email: r.wilbert3@gmail.com
name: Charleston Dash & Bash
url: 'https://thegrid.ai/CharlestonDashnBash'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Raison` de Race
    id: abb0647c-c66a-4ba1-a8e4-25b7b39ba282
    type: content
  - name: Registration
    id: 34b594bf-61d3-42c4-93d6-aae73f039c8f
    type: content
  - name: Food & Drink
    id: 68133cd8-edad-48cd-a151-6e1708772b4c
    type: content
  - name: Signup / Q&A
    id: 7fcab46f-5ff0-4e35-868d-9c3f288224bb
    type: content
  - name: Wounded Nature.org
    url: 'http://woundednature.org/'
    type: external
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FntELNM3XgIE%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DntELNM3XgIE&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FntELNM3XgIE%2Fhqdefault.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Robert Wilbert
          url: 'https://www.youtube.com/user/rfwilbert3'
          avatar: {}
      related: []
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vfl8qSV2F.ico'
        domain: youtu.be
      keywords:
        - ''
      description: Uploaded by Robert Wilbert on 2018-06-14.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=ntELNM3XgIE&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=ntELNM3XgIE&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=ntELNM3XgIE&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=ntELNM3XgIE&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=ntELNM3XgIE&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=ntELNM3XgIE'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=ntELNM3XgIE
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=ntELNM3XgIE
          package: '544007664'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://youtu.be/ntELNM3XgIE'
      title: Dash n Bash
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ' '
purpose:
  - type: internal
    label: About us
    item: abb0647c-c66a-4ba1-a8e4-25b7b39ba282
  - type: internal
    label: Race Info
    item: ee7ee927-8a0c-4a50-8518-2c29f1fb4849
