typography_spectrum: 0.41560873304493723
color:
  brandColors:
    - '#8CC63E'
    - '#00BFF3'
    - '#F15927'
    - '#434343'
    - '#FEFFFF'
  brandStrength: 0.5212071022929827
  lightness: 0.03891840575253683
  saturation: 0.6427184913068604
  rhythmicContrast: 0.6041641040064284
github: true
layout_spectrum: 0.7624284483256316
author:
  name: eSecurity Consulting Servces
  email: r.wilbert3@gmail.com
name: Charleston Dash & Bash
url: 'https://thegrid.ai/CharlestonDashnBash'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Be a Part of the Cure
    id: abb0647c-c66a-4ba1-a8e4-25b7b39ba282
    type: content
  - name: Registration
    id: 34b594bf-61d3-42c4-93d6-aae73f039c8f
    type: content
  - name: Food & Drink
    id: 68133cd8-edad-48cd-a151-6e1708772b4c
    type: content
  - name: Signup / Q&A
    id: 7fcab46f-5ff0-4e35-868d-9c3f288224bb
    type: content
  - name: Wounded Nature.org
    url: 'http://woundednature.org/'
    type: external
  - name: Party Time
    id: a69b1219-40e7-48c3-8717-3ddfb45f1cf9
    type: content
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>Dash n Bash.mp4</h1><p>Dropbox is a free service that lets
      you bring your photos, docs, and videos anywhere and share them easily.
      Never email yourself a file again!</p><img
      src="https://www.dropbox.com/temp_thumb_from_token/s/mcvuqpehdbj19ge?preserve_transparency=False&size=1024x1024&size_mode=2"></article>
    src: >-
      https://www.dropbox.com/temp_thumb_from_token/s/mcvuqpehdbj19ge?preserve_transparency=False&size=1024x1024&size_mode=2
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://www.dropbox.com'
        name: Dropbox
        favicon: 'https://cfl.dropboxstatic.com/static/images/favicon-vflUeLeeY.ico'
        domain: www.dropbox.com
      keywords: []
      description: >-
        Dropbox is a free service that lets you bring your photos, docs, and
        videos anywhere and share them easily. Never email yourself a file
        again!
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: 'https://www.dropbox.com/s/mcvuqpehdbj19ge/Dash%20n%20Bash.mp4?dl=0'
      title: Dash n Bash.mp4
      datePublished: null
    title: Dash n Bash.mp4
    caption: >-
      Dropbox is a free service that lets you bring your photos, docs, and
      videos anywhere and share them easily. Never email yourself a file again!
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose:
  - type: external
    url: 'https://www.dropbox.com/s/mcvuqpehdbj19ge/Dash%20n%20Bash.mp4?dl=0'
    label: Show Me Around
