typography_spectrum: 0.41560873304493723
color:
  brandColors:
    - '#8CC63E'
    - '#00BFF3'
    - '#F15927'
    - '#434343'
    - '#FEFFFF'
  brandStrength: 0.5212071022929827
  lightness: 0.03891840575253683
  saturation: 0.6427184913068604
  rhythmicContrast: 0.6041641040064284
github: true
layout_spectrum: 0.7624284483256316
author:
  name: eSecurity Consulting Servces
  email: r.wilbert3@gmail.com
name: Charleston Dash & Bash
url: 'https://thegrid.ai/CharlestonDashnBash'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Raison` de Race
    id: abb0647c-c66a-4ba1-a8e4-25b7b39ba282
    type: content
  - name: Registration
    id: 34b594bf-61d3-42c4-93d6-aae73f039c8f
    type: content
  - name: Food & Drink
    id: 68133cd8-edad-48cd-a151-6e1708772b4c
    type: content
  - name: Signup / Q&A
    id: 7fcab46f-5ff0-4e35-868d-9c3f288224bb
    type: content
  - name: Wounded Nature.org
    url: 'http://woundednature.org/'
    type: external
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: article
    html: >-
      <article><h1>Dash n Bash.mp4</h1><img
      src="https://lh4.googleusercontent.com/xZ4srEk8t0IChEfuNMEpBUXuq38mIXwEcsyc73H_yCIzyiJcsIxxMtfRu3A=w1200-h630-p"></article>
    src: >-
      https://lh4.googleusercontent.com/xZ4srEk8t0IChEfuNMEpBUXuq38mIXwEcsyc73H_yCIzyiJcsIxxMtfRu3A=w1200-h630-p
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://drive.google.com'
        name: Google Drive
        favicon: 'https://ssl.gstatic.com/docs/doclist/images/icon_14_video_favicon.ico'
        domain: drive.google.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://drive.google.com/file/d/1xrxTYyBLs_vnIlvTytKkWIONOtYZ4zmy/view?usp=sharing
      title: Dash n Bash.mp4
      datePublished: null
    title: Dash n Bash.mp4
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ' '
purpose:
  - type: internal
    label: About us
    item: abb0647c-c66a-4ba1-a8e4-25b7b39ba282
  - type: internal
    label: Race Info
    item: ee7ee927-8a0c-4a50-8518-2c29f1fb4849
